import React, { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import '../NavBarSection/finalReports.css';

function FinalReports() {
  const [dateFrom, setDateFrom] = useState('08/08/2024');
  const [dateTo, setDateTo] = useState('08/08/2024');
  const [category, setCategory] = useState('');

  const handlePrint = () => {
    const doc = new jsPDF();
    doc.text('Final Reports', 14, 16);
    doc.text(`Reporting Date: From ${dateFrom} To ${dateTo}`, 14, 22);

    const tableColumn = ["Hospital No.", "Patient Name", "Age/Sex", "Phone Number", "Test Name", "Report Generated By", "Requesting Dept.", "Run No.", "Bar Code", "Is Printed"];
    const tableRows = [];

    // Example row data; you would replace this with your actual data
    const rowData = ["12345", "John Doe", "25/M", "123-456-7890", "Blood Test", "Dr. Smith", "ER", "001", "123456", "No"];
    tableRows.push(rowData);

    doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 30,
    });

    // Generate the PDF and open in a new tab
    const pdfData = doc.output('dataurlstring');
    const newWindow = window.open();
    if (newWindow) {
      newWindow.document.write(
        `<iframe src="${pdfData}" width="100%" height="100%" style="border:none;"></iframe>`
      );
    }
  };

  return (
    <div className="finalReports-work-list">
      <h4>Final Reports</h4>
      <div className="finalReports-header">
        <div className="finalReports-ReportingDate">Reporting Date:</div>
        <div className="finalReports-date-range">
          <label>From:</label>
          <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} />
          <label>To:</label>
          <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} />
        </div>
        <div className="finalReports-category-select">
          <label>Category:</label>
          <select value={category} onChange={(e) => setCategory(e.target.value)}>
            <option value="">--Select Lab Category--</option>
            <option value="">Sellect All</option>
            <option value="">Search</option>
            <option value="">Biochemistry</option>
            <option value="">Hematology</option>
            <option value="">Microbiology</option>
            <option value="">Parasitology</option>
            <option value="">Serology</option>
            <option value="">Immunoassay</option>
            <option value="">DEFAULT</option>
            <option value="">HISTOCYTOLOGY</option>
            <option value="">OUT SOURCE</option>
            <option value="">MOLECULAR BIOCHEMISTRY</option>
            <option value="">PATHOLOGY</option>
            <option value="">TUMOR MARKER</option>
            <option value="">VIROLOGY</option>
            <option value="">Blood Transfusion</option>
          </select>
        </div>
        <button className="finalReports-load-button">Load <i className="fa-solid fa-rotate"></i></button>
      </div>

      <div className="finalReports-searchbar-N-showing">
        <div className="finalReports-search-bar">
        
          <i className="fa-solid fa-magnifying-glass"></i>
          <input type="text" placeholder="Search..." />
        </div>
        <div className="finalReports-results-info">
          <span>Showing 0 / 0 results</span>
          <button className="finalReports-print-button" onClick={handlePrint}>
            Print
          </button>
        </div>
      </div>

      <div className="finalReports-work-table">
        <table className="finalReports-work-table">
          <thead>
            <tr>
              <th>Hospital No.</th>
              <th>Patient Name</th>
              <th>Age/Sex</th>
              <th>Phone Number</th>
              <th>Test Name</th>
              <th>Report Generated By</th>
              <th>Requesting Dept.</th>
              <th>Run No.</th>
              <th>Bar Code</th>
              <th>Is Printed</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colSpan="11">Loading...</td>
            </tr>
          </tbody>
        </table>

        <div className="finalReports-pagination">
          <span>0 to 0 of 0</span>
          <button>First</button>
          <button>Previous</button>
          <span>Page 0 of 0</span>
          <button>Next</button>
          <button>Last</button>
        </div>
        
      </div>
    </div>
  );
}

export default FinalReports;
